# Position Controllers ---------------------------------------
# Publish all joint states -----------------------------------
joint_state:
  type: joint_state_controller/JointStateController
  publish_rate: 50

position:
  type: effort_controllers/JointPositionController
  joint: camera_joint
  pid: {p: 100.0, i: 0.01, d: 2.0}
